### ISSUE TITLE
Getting error because GlobalKey<_RectGetterState> uses private type

### ISSUE THREAD

**Issue by alectogeek** [debuggerx01/rect_getter#6]
I see the following error because I can't specify type of created global key:
![image](https://user-images.githubusercontent.com/18165303/141656565-a1bddcbe-bb8a-4dbb-843f-086074170471.png)

**Comment by debuggerx01** [comment]
Show me your `flutter doctor` info pls :)

**Comment by alectogeek** [comment]
Here it is:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)
    ! Error: Starlink is not connected. Xcode will continue when Starlink is connected. (code
      -13)

```

**Comment by debuggerx01** [comment]
> Here it is:
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-DE)
> [!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     ✗ cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
> [✓] Xcode - develop for iOS and macOS
> [✓] Android Studio (version 4.1)
> [✓] Connected device (1 available)
>     ! Error: Starlink is not connected. Xcode will continue when Starlink is connected. (code
>       -13)
> ```

Did you add `strong-mode:
    implicit-casts: false` in `analysis_options.yaml` ?

**Comment by alectogeek** [comment]
![image](https://user-images.githubusercontent.com/18165303/141965301-c9ddf73f-e886-4027-be46-a10752e73fcd.png)

**Comment by debuggerx01** [comment]
Well, I got the same error after configuring this option. I will update it later.
